---
# Installing redis 

- name: Updating repository
  become: yes
  apt:
    update_cache: yes


- name: Adding GPG public key
  become: yes
  apt_key: 
    url: "{{ gpg_public_key_url }}"
    state: present


- name: Adding Sensu repo to apt source
  become: yes
  apt_repository:
    repo: deb {{ repo_url }}/apt {{ ansible_distribution_release }} main


- name: Update repo and Install Sensu
  become: yes
  apt: 
    name: sensu
    update_cache: yes
    state: present

- name: Updating cache and Installing redis
  become: yes
  apt:
   name: redis-server
   update_cache: yes
   state: present


- name: Updating redis configuration file
  become: yes
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind 127.0.0.1'
    line: 'bind 0.0.0.0'


- name: Restart redis-server
  become: yes
  shell: '/etc/init.d/redis-server restart'