---
# Installing rabbitmq


- name: Updating repository
  become: yes
  apt:
    update_cache: yes


- name: Adding GPG public key
  become: yes
  apt_key: 
    url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
    state: present


- name: Adding Sensu repo to apt source
  become: yes
  apt_repository:
    repo: deb https://sensu.global.ssl.fastly.net/apt {{ ansible_distribution_release }} main


- name: Update repo and Install Sensu
  become: yes
  apt: 
    name: sensu
    update_cache: yes
    state: present


- name: Updating repository
  become: yes
  apt:
    update_cache: yes


- name: Download Erlang packages to destination machine
  become: yes
  get_url:
    url: http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /tmp/erlang-solutions_1.0_all.deb


- name: Add the Erlang Solutions APT repository
  become: yes
  apt: deb="/tmp/erlang-solutions_1.0_all.deb"


- name: Updating repository and Install Erlang
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
        - 'socat' 
        - 'erlang-base'
        - 'erlang-nox'


- name: Download rabbitmq package
  become: yes
  get_url:
    url: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server_3.6.9-1_all.deb
    dest: /tmp/rabbitmq-server_3.6.9-1_all.deb


- name: Install rabbitmq
  become: true
  apt: deb="/tmp/rabbitmq-server_3.6.9-1_all.deb"


- name: Restart rabbitmq service
  apt: 
  notify: restart rabbitmq service


- name: Ensure RabbitMQ is running
  become: yes
  service:
    name: rabbitmq-server
    state: started
    enabled: true
    

- name: Wait for RabbitMQ to be up and running before asking to create a vhost
  pause: seconds=3


# Configuring Rabbitmq

- name: Creating rabbitmq virtual host
  become: yes
  rabbitmq_vhost:
    name: /{{rabbit_vhost}}
    state: present


- name: Creating rabbitmq user and setting set_permissions
  become: yes
  rabbitmq_user:
    user: "{{rabbit_user}}"
    password: "{{rabbit_pass}}"
    permissions:
      - vhost: /{{rabbit_vhost}}
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present


- name: Restart rabbitmq service
  apt:
  notify: restart rabbitmq service