---
# Installing rabbitmq

- name: Adding GPG public key
  become: yes
  apt_key: 
    url: "{{ gpg_public_key_url }}"
    state: present


- name: Adding Sensu repo to apt source
  become: yes
  apt_repository:
    repo: deb "{{ repo_url }}"/apt {{ ansible_distribution_release }} main


- name: Update repo and Install Sensu
  become: yes
  apt: 
    name: sensu
    update_cache: yes
    state: present


- name: Download Erlang packages to destination machine
  become: yes
  get_url:
    url: "{{ erlang_url }}/{{ erlang_package_deb }}"
    dest: "{{ path_of_erlang_deb }}/{{ erlang_package_deb }}"


- name: Add the Erlang Solutions APT repository
  become: yes
  apt: deb= "{{ path_of_erlang_deb }}/{{ erlang_package_deb }}"


- name: Updating repository and Install Erlang
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
        - 'socat' 
        - 'erlang-base'
        - 'erlang-nox'


- name: Download rabbitmq package
  become: yes
  get_url:
    url: "{{ rabbitmq_url_deb }}/{{ rabbitmq_deb_package_name }}"
    dest: "{{ path_of_rabbitmq_deb }}/{{ rabbitmq_deb_package_name }}"


- name: Install rabbitmq
  become: true
  apt:
     deb: "{{ rabbitmq_url_deb }}/{{ rabbitmq_deb_package_name }}" 


- name: Restart rabbitmq service
  apt: 
  notify: restart rabbitmq service


- name: Wait for RabbitMQ to be up and running before asking to create a vhost
  pause: seconds=3


- name: Ensure RabbitMQ is running
  become: yes
  service:
    name: rabbitmq-server
    state: started
    enabled: true


# Configuring Rabbitmq

- name: Creating rabbitmq virtual host
  become: yes
  rabbitmq_vhost:
    name: /{{rabbit_vhost}}
    state: present


- name: Creating rabbitmq user and setting set_permissions
  become: yes
  rabbitmq_user:
    user: "{{rabbit_user}}"
    password: "{{rabbit_pass}}"
    permissions:
      - vhost: /{{rabbit_vhost}}
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present


- name: Restart rabbitmq service
  apt:
  notify: restart rabbitmq service
