---

- name: Ensure telemetryreports dir is not present
  file:
    path: "{{ repo_path}}"
    state: absent

- name: Get updated files from git repository 
  git: 
   repo: "https://harshavardhanc:Harsha_1122@github.com/DIKSHA-NCTE/telemetryreports.git"
   dest: "{{ repo_path}}"

- name: tmp tasks
  shell: "git checkout portal_dashboards"
  args:
    chdir: "{{ repo_path }}"

- name: executing the commands
  shell: "{{ item }}"
  with_items:
    - source /mount/venv/bin/activate
    - python "{{ repo_path }}"/scripts/content_creation.py "{{ data_path }}"
  args:
    executable: /bin/bash
