# Rabbitmq_vars

rabbit_vhost: sensu
rabbit_user: sensu
rabbit_pass: secret

# Uchiwa_vars
uchiwa_dashboard_user: admin
uchiwa_dashboard_user_password: admin


# Environment_Name
environment_name: test
